plugins/__init__.py

Fixed error reporting for templates

---

plugins/resources.py

small but critical issue on the ServiceService handler

fixed issue with broken service handler

---

plugins/__init__.py
tests/test_unknown.py

Add is_unknown method

---

plugins/__init__.py
tests/test_get_attribute.py

Add tests for get_attribute

---

CHANGELOG.md
module.yml
plugins/__init__.py

Remove first_of and get plugins

---

CHANGELOG.md
module.yml
plugins/__init__.py
tests/test_template.py

Support current dir in paths

---

setup.cfg
tests/conftest.py
tests/test_file.py
tests/test_in_docker.py
tests/test_mutables.py
tests/test_plugins.py
tests/test_template.py
tests/test_types.py

Fix flake8-copyright config

---

tests/conftest.py

Stop the container before we create a new one.
Related to [infra #70](https://github.com/inmanta/infra-tickets/issues/70)
```sh
git pull
git pull
git push
```

Stop container if it is running

---

tests/test_template.py

* Short description here *
```sh
git pull
git pull
git push
```

Test fixes

---

requirements.dev.txt

```sh
git pull
git pull
git push
```

Revert pytest-inmanta to working version until fixed

---

plugins/__init__.py
requirements.dev.txt

added support for pytest-inmanta~=2.0
part of inmanta/pytest-inmanta#248
```sh
git pull
git pull
git push
```

added support for pytest-inmanta~=2.0

---

.github/dependabot.yml

Resume version bumps for Jinja2.

Resume version bumps for Jinja2

---

plugins/resources.py

Unless I'm mistaken #329 introduced a redundant condition. The lines it added already exist 2 lines up.
I'm not planning to bump the version for this change.
```sh
git pull
git pull
git push
```

removed redundant condition

---

tests/conftest.py

closes https://github.com/inmanta/std/issues/450
2. tag and bump
```sh
git pull
git push
```
3. Remove the branch

Support running test using a python3.11 venv

---

.ci-integration-tests.yml
CHANGELOG.md

Make sure to run the std module for iso6 against python3.9.

Run tests against python3.9

---

.ci-integration-tests.yml
CHANGELOG.md

Make sure to run the std module for iso4 against python3.6.

Run tests against python3.6

---

CHANGELOG.md
model/_init.cf
module.yml

Added the DiscoveryResource entity.
Part of inmanta/inmanta-core#6025

Added the DiscoveryResource entity

---

CHANGELOG.md
model/_init.cf

This [PR](https://github.com/inmanta/std/pull/468) introduced an error: Version should stay a number.
2. tag and bump
```sh
git pull
git push
```
3. Remove the branch

fix issue number/int

---

CHANGELOG.md
plugins/__init__.py

Deprecate obsolete plugins from std.
closes https://github.com/inmanta/std/issues/470
2. tag and bump
```sh
git pull
git push
```
3. Remove the branch

Deprecate obsolete plugins.

---

CHANGELOG.md
module.yml
plugins/__init__.py

Moved some plugins over from athonet_mpn and added support for keep_prefix index
2. tag and bump
```sh
git pull
git push
```
3. Remove the branch

Add limit and ip_address_from_interface plugins and support for keep_prefix on ipindex

---

.github/pull_request_template.md

stage 2 for https://github.com/inmanta/lsm/pull/765/files

updated pr template

---

CHANGELOG.md
requirements.dev.txt
requirements.txt

* Short description here *
```sh
git pull
git push
```

Pin pytest

---

.ci-integration-tests.yml
Makefile
requirements.dev.txt

Add a constraint to Inmanta core for ISO7 through the `CI-install` target.
```sh
git pull
git push
```

Constrain core ISO7

---

README.md

Fix incorrect information in Readme
```sh
git pull
git push
```

Fix readme info

---

README.md

Small fix to the title of the readme
```sh
git pull
git push
```

Change README.md title

---

CHANGELOG.md
model/_init.cf

Add the `receive_events` boolean to `std::Resource`. If approved, I'll add it on master as well.
closes #549
```sh
git pull
git push
```

added receive_events attribute

---

CHANGELOG.md
model/_init.cf
tests/test_mutables.py

- Removed usage of number type
closes https://github.com/inmanta/std/issues/548
```sh
git pull
git push
```

Remove usage of number type

---

CHANGELOG.md
module.yml
plugins/__init__.py

closes  https://github.com/inmanta/std/issues/455
```sh
git pull
git push
```

Remove deprecated 'offset' parameter in 'sequence' plugin

---

CHANGELOG.md
plugins/__init__.py

Restored compatibility with Python 3.11. I don't like the verbosity, but it can't be helped.
```sh
git pull
git push
```

python 3.11 compatibility

---

plugins/__init__.py

* Short description here *
```sh
git pull
git push
```

remove fact reference warning

---

plugins/__init__.py

This method was apparently used by the `config` module
```sh
git pull
git push
```

restored backwards compatibility for jinja proxy
